title: AI pro se
description: AI-guided self-help for **AI** *pro se* litigants.
url: https://kaso.law
baseurl: ""
openai_public_api_key: ""
openai_client_model: gpt-5.4
openai_reporter_model: gpt-5.2
server_api_base_url: ""
markdown: kramdown
kramdown:
  input: GFM
